name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Generate-Token:
    runs-on: ubuntu-latest
    container:
      image: victorfconti/application_tag_creator:latest
      volumes:
        - application.toml:/application.toml
    steps:
      - name: "Generate token"
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
