name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Show-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Show files
        run: ls
  Generate-Token:
    runs-on: ubuntu-latest
    container:
      image: victorfconti/application_tag_creator:latest
      volumes:
        - application.toml:/app/application.toml
    steps:
      - name: "Generate token"
        run: cd /app; python main.py
