name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Show-Files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show files
        run: ls

  Generate-Token:
    runs-on: ubuntu-latest
    container:
      image: victorfconti/application_tag_creator:latest
    steps:
      - uses: actions/checkout@v1
      - name: "Generate token"
        run: | 
          cp application.toml /app;
          cd /app;
          python main.py
