name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Generate-Token:
    runs-on: ubuntu-latest
    container:
      image: victorfconti/application_tag_creator:latest
    steps:
      - uses: actions/checkout@v1
      - name: "Generate token"
        run: | 
          cp application.toml /app;
          cd /app;
          token=`python main.py`;
          echo "application_token=$token" >> "$GITHUB_ENV";
      - name: "Save token"
        run: |
          curl -s -X POST --header "X-Vault-Token: ${{ secrets.VAULT_TOKEN }}" --header "X-Vault-Namespace: ${{ secrets.VAULT_NAMESPACE }}"  \
          -d '{"token":{"value":"$GITHUB_ENV.application_token"}}'   $VAULT_ADDR/v1/kv/application
